blank_issues_enabled: false
contact_links:
  - name: Report an Issue
    url: https://github.com/davidadas/rebellion2/issues/new?template=bug_report.yml
    about: Open the Rebellion 2 issue form.
  - name: Request a Feature
    url: https://github.com/davidadas/rebellion2/issues/new?template=feature_request.yml
    about: Open the Rebellion 2 feature request form.
